### ISSUE TITLE
Created books cannot be applied

### ISSUE THREAD

**Issue by Kachajal** [Dyonovan/SimplyEnchanting#2]
There's something broken with newly created books using the Book Enchanter. They appear to have the enchantment, but cannot be applied in an anvil. 

Using Minecraft 1.11.2, Forge 13.20.0.2228, no other mods.

**Comment by Dyonovan** [comment]
Fixed. Sorry about that should have tested that.

**Comment by Kachajal** [comment]
Very nice, thank you!

And don't worry. Two of us "tested" the mod and applied it to our server, because we just didn't think to check if the books really worked, either. So you're not the only one :P
